services:
  # PostgreSQL Database
  postgres: #host-name-adress
    image: postgres:16-alpine
    container_name: fastapi_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} #maintance database
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fastapi_network

  # PgAdmin - Web Database Management
  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: fastapi_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fastapi_network

volumes:
  postgres_data:
    name: fastapi_postgres_data
  pgadmin_data:
    name: fastapi_pgadmin_data

networks:
  fastapi_network:
    name: fastapi_network
    driver: bridge
